language: java
dist: trusty
script: gradle build
deploy:
  provider: releases
  api_key:
    secure: $API_KEY
  file_glob: true
  file: build/libs/cassandra_exporter*.jar
  skip_cleanup: true
  on:
    tags: true
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=criteord/cassandra_exporter
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - cd docker; docker build -f Dockerfile -t $REPO:$TAG .
  - docker tag $REPO:$TAG $REPO:latest
  - docker push $REPO
